name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node: [14.x, 16.x, 18.x]
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@v3.3
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v3.6
              with:
                  node-version: ${{ matrix.node }}
            - run: yarn run build --if-present
            - run: yarn test
              env:
                  CI: true
